services:
  # default configuration for services in *this* file
  _defaults:
    # automatically injects dependencies in your services
    autowire: true
    # automatically registers your services as commands, event subscribers, etc.
    autoconfigure: true
    # this means you cannot fetch services directly from the container via $container->get()
    # if you need to do this, you can override this setting on individual services
    public: false

  Concerto\PanelBundle\:
    resource: '../../{Command,DAO,EventSubscriber,Service}'

    # controllers are imported separately to make sure they're public
    # and have a tag that allows actions to type-hint services
  Concerto\PanelBundle\Controller\:
    resource: '../../Controller'
    public: true
    tags: ['controller.service_arguments']

  concerto_panel.locale_subscriber:
    class: Concerto\PanelBundle\EventSubscriber\LocaleSubscriber
    arguments: ["%kernel.default_locale%"]
    tags:
      - { name: kernel.event_subscriber }          
      
  concerto_panel.entity_subscriber:
    class: Concerto\PanelBundle\EventSubscriber\EntitySubscriber
    tags:
      - { name: doctrine.event_subscriber }       
           
#   DataTable
  concerto_panel.DataTable_metadata:
    class: Doctrine\ORM\Mapping\ClassMetadata
    arguments: ["Concerto\\PanelBundle\\Entity\\DataTable"]
  concerto_panel.DataTable_repository:
    class: Concerto\PanelBundle\Repository\DataTableRepository
    arguments: ["@doctrine.orm.entity_manager","@concerto_panel.DataTable_metadata"]
  concerto_panel.db_structure_dao:
    class: Concerto\PanelBundle\DAO\DBStructureDAO
    arguments: ["@database_connection", "@logger"]
  concerto_panel.db_data_dao:
    class: Concerto\PanelBundle\DAO\DBDataDAO
    arguments: ["@database_connection"]
  concerto_panel.db_structure_service:
    class: Concerto\PanelBundle\Service\DBStructureService
    arguments: ["@concerto_panel.db_structure_dao", "@logger"]
  concerto_panel.DataTable_service:
    class: Concerto\PanelBundle\Service\DataTableService
    arguments: ["@concerto_panel.DataTable_repository","@validator","@concerto_panel.db_structure_service","@concerto_panel.db_data_dao", "@security.authorization_checker"]
    
#   Panel
  concerto_panel.panel_service:
    class: Concerto\PanelBundle\Service\PanelService
    
#   Home
  concerto_panel.home_service:
    class: Concerto\PanelBundle\Service\HomeService
    arguments: ["@concerto_panel.Test_repository"]
    
#   File
  concerto_panel.file_service:
    class: Concerto\PanelBundle\Service\FileService
    arguments: ["%kernel.environment%"]
    
#   Test
  concerto_panel.Test_metadata:
    class: Doctrine\ORM\Mapping\ClassMetadata
    arguments: ["Concerto\\PanelBundle\\Entity\\Test"]
  concerto_panel.Test_repository:
    class: Concerto\PanelBundle\Repository\TestRepository
    arguments: ["@doctrine.orm.entity_manager","@concerto_panel.Test_metadata"]
  concerto_panel.Test_service:
    class: Concerto\PanelBundle\Service\TestService
    arguments: ["@concerto_panel.Test_repository","@validator","@slugify","@concerto_panel.TestVariable_service","@concerto_panel.TestWizard_repository","@concerto_panel.TestNode_service","@concerto_panel.TestNodeConnection_service","@concerto_panel.TestNodePort_service","@security.authorization_checker"]
    
#   TestNode
  concerto_panel.TestNode_metadata:
    class: Doctrine\ORM\Mapping\ClassMetadata
    arguments: ["Concerto\\PanelBundle\\Entity\\TestNode"]
  concerto_panel.TestNode_repository:
    class: Concerto\PanelBundle\Repository\TestNodeRepository
    arguments: ["@doctrine.orm.entity_manager","@concerto_panel.TestNode_metadata"]
  concerto_panel.TestNode_service:
    class: Concerto\PanelBundle\Service\TestNodeService
    arguments: ["@concerto_panel.TestNode_repository","@validator","@concerto_panel.TestNodePort_service","@concerto_panel.TestVariable_service","@concerto_panel.Test_repository", "@security.authorization_checker"]
    
#   TestNodePort
  concerto_panel.TestNodePort_metadata:
    class: Doctrine\ORM\Mapping\ClassMetadata
    arguments: ["Concerto\\PanelBundle\\Entity\\TestNodePort"]
  concerto_panel.TestNodePort_repository:
    class: Concerto\PanelBundle\Repository\TestNodePortRepository
    arguments: ["@doctrine.orm.entity_manager","@concerto_panel.TestNodePort_metadata"]
  concerto_panel.TestNodePort_service:
    class: Concerto\PanelBundle\Service\TestNodePortService
    arguments: ["@concerto_panel.TestNodePort_repository","@validator","@concerto_panel.TestVariable_repository","@concerto_panel.TestNode_repository", "@security.authorization_checker", "@logger"]
    
#   TestNodeConnection
  concerto_panel.TestNodeConnection_metadata:
    class: Doctrine\ORM\Mapping\ClassMetadata
    arguments: ["Concerto\\PanelBundle\\Entity\\TestNodeConnection"]
  concerto_panel.TestNodeConnection_repository:
    class: Concerto\PanelBundle\Repository\TestNodeConnectionRepository
    arguments: ["@doctrine.orm.entity_manager","@concerto_panel.TestNodeConnection_metadata"]
  concerto_panel.TestNodeConnection_service:
    class: Concerto\PanelBundle\Service\TestNodeConnectionService
    arguments: ["@concerto_panel.TestNodeConnection_repository","@validator","@concerto_panel.Test_repository","@concerto_panel.TestNode_repository","@concerto_panel.TestNodePort_repository", "@security.authorization_checker"]
    
#   TestWizard
  concerto_panel.TestWizard_metadata:
    class: Doctrine\ORM\Mapping\ClassMetadata
    arguments: ["Concerto\\PanelBundle\\Entity\\TestWizard"]
  concerto_panel.TestWizard_repository:
    class: Concerto\PanelBundle\Repository\TestWizardRepository
    arguments: ["@doctrine.orm.entity_manager","@concerto_panel.TestWizard_metadata"]
  concerto_panel.TestWizard_service:
    class: Concerto\PanelBundle\Service\TestWizardService
    arguments: ["@concerto_panel.TestWizard_repository","@validator","@concerto_panel.Test_service","@concerto_panel.TestVariable_service","@concerto_panel.TestNodePort_service","@concerto_panel.TestWizardStep_service","@concerto_panel.TestWizardParam_service","@security.authorization_checker"]
    
#   TestWizardStep
  concerto_panel.TestWizardStep_metadata:
    class: Doctrine\ORM\Mapping\ClassMetadata
    arguments: ["Concerto\\PanelBundle\\Entity\\TestWizardStep"]
  concerto_panel.TestWizardStep_repository:
    class: Concerto\PanelBundle\Repository\TestWizardStepRepository
    arguments: ["@doctrine.orm.entity_manager","@concerto_panel.TestWizardStep_metadata"]
  concerto_panel.TestWizardStep_service:
    class: Concerto\PanelBundle\Service\TestWizardStepService
    arguments: ["@concerto_panel.TestWizardStep_repository","@validator","@concerto_panel.TestWizard_repository", "@security.authorization_checker"]
    
#   TestWizardParam
  concerto_panel.TestWizardParam_metadata:
    class: Doctrine\ORM\Mapping\ClassMetadata
    arguments: ["Concerto\\PanelBundle\\Entity\\TestWizardParam"]
  concerto_panel.TestWizardParam_repository:
    class: Concerto\PanelBundle\Repository\TestWizardParamRepository
    arguments: ["@doctrine.orm.entity_manager","@concerto_panel.TestWizardParam_metadata"]
  concerto_panel.TestWizardParam_service:
    class: Concerto\PanelBundle\Service\TestWizardParamService
    arguments: ["@concerto_panel.TestWizardParam_repository","@validator","@concerto_panel.TestVariable_service","@concerto_panel.TestWizard_repository","@concerto_panel.TestWizardStep_repository", "@security.authorization_checker", "@concerto_panel.TestNodePort_service", "@logger"]
    
#   TestSessionLog
  concerto_panel.TestSessionLog_metadata:
    class: Doctrine\ORM\Mapping\ClassMetadata
    arguments: ["Concerto\\PanelBundle\\Entity\\TestSessionLog"]
  concerto_panel.TestSessionLog_repository:
    class: Concerto\PanelBundle\Repository\TestSessionLogRepository
    arguments: ["@doctrine.orm.entity_manager","@concerto_panel.TestSessionLog_metadata"]
  concerto_panel.TestSessionLog_service:
    class: Concerto\PanelBundle\Service\TestSessionLogService
    arguments: ["@concerto_panel.TestSessionLog_repository", "@concerto_panel.Test_service", "@security.authorization_checker"]
    
#   TestVariable
  concerto_panel.TestVariable_metadata:
    class: Doctrine\ORM\Mapping\ClassMetadata
    arguments: ["Concerto\\PanelBundle\\Entity\\TestVariable"]
  concerto_panel.TestVariable_repository:
    class: Concerto\PanelBundle\Repository\TestVariableRepository
    arguments: ["@doctrine.orm.entity_manager","@concerto_panel.TestVariable_metadata"]
  concerto_panel.TestVariable_service:
    class: Concerto\PanelBundle\Service\TestVariableService
    arguments: ["@concerto_panel.TestVariable_repository","@validator", "@concerto_panel.TestNodePort_service", "@concerto_panel.TestNodeConnection_service", "@concerto_panel.Test_repository", "@security.authorization_checker"]
 
#   Role
  concerto_panel.Role_metadata:
    class: Doctrine\ORM\Mapping\ClassMetadata
    arguments: ["Concerto\\PanelBundle\\Entity\\Role"]
  concerto_panel.Role_repository:
    class: Concerto\PanelBundle\Repository\RoleRepository
    arguments: ["@doctrine.orm.entity_manager","@concerto_panel.Role_metadata"]  
    
#   User
  concerto_panel.User_metadata:
    class: Doctrine\ORM\Mapping\ClassMetadata
    arguments: ["Concerto\\PanelBundle\\Entity\\User"]
  concerto_panel.User_repository:
    class: Concerto\PanelBundle\Repository\UserRepository
    arguments: ["@doctrine.orm.entity_manager","@concerto_panel.User_metadata"]
  concerto_panel.User_service:
    class: Concerto\PanelBundle\Service\UserService
    arguments: ["@concerto_panel.User_repository","@concerto_panel.Role_repository","@validator","@security.encoder_factory", "@security.authorization_checker", "%uio%", "@concerto_panel.import_service"]
    
#   ViewTemplate
  concerto_panel.ViewTemplate_metadata:
    class: Doctrine\ORM\Mapping\ClassMetadata
    arguments: ["Concerto\\PanelBundle\\Entity\\ViewTemplate"]
  concerto_panel.ViewTemplate_repository:
    class: Concerto\PanelBundle\Repository\ViewTemplateRepository
    arguments: ["@doctrine.orm.entity_manager","@concerto_panel.ViewTemplate_metadata"]
  concerto_panel.ViewTemplate_service:
    class: Concerto\PanelBundle\Service\ViewTemplateService
    arguments: ["@concerto_panel.ViewTemplate_repository","@validator", "@security.authorization_checker"] 
    
#   TestSession
  concerto_panel.TestSession_metadata:
    class: Doctrine\ORM\Mapping\ClassMetadata
    arguments: ["Concerto\\PanelBundle\\Entity\\TestSession"]
  concerto_panel.TestSession_repository:
    class: Concerto\PanelBundle\Repository\TestSessionRepository
    arguments: ["@doctrine.orm.entity_manager","@concerto_panel.TestSession_metadata"]
  concerto_panel.TestSession_service:
    class: Concerto\PanelBundle\Service\TestSessionService
    arguments: ["%kernel.environment%", "@concerto_panel.TestSession_repository","@concerto_panel.Test_repository","@concerto_panel.TestSessionLog_repository", "%panel_nodes%","%secret%","@logger", "@concerto_test.r_runner_service", "@concerto_panel.file_service","@concerto_panel.Administration_service", "@concerto_panel.LoadBalancer_service", "%test_runner_settings%", "@session"]
    
# Administration
  concerto_panel.AdministrationSetting_metadata:
    class: Doctrine\ORM\Mapping\ClassMetadata
    arguments: ["Concerto\\PanelBundle\\Entity\\AdministrationSetting"]
  concerto_panel.AdministrationSetting_repository:
    class: Concerto\PanelBundle\Repository\AdministrationSettingRepository
    arguments: ["@doctrine.orm.entity_manager","@concerto_panel.AdministrationSetting_metadata"]
  concerto_panel.Message_metadata:
    class: Doctrine\ORM\Mapping\ClassMetadata
    arguments: ["Concerto\\PanelBundle\\Entity\\Message"]
  concerto_panel.Message_repository:
    class: Concerto\PanelBundle\Repository\MessageRepository
    arguments: ["@doctrine.orm.entity_manager","@concerto_panel.Message_metadata"]
  concerto_panel.ScheduledTask_metadata:
    class: Doctrine\ORM\Mapping\ClassMetadata
    arguments: ["Concerto\\PanelBundle\\Entity\\ScheduledTask"]
  concerto_panel.ScheduledTask_repository:
    class: Concerto\PanelBundle\Repository\ScheduledTaskRepository
    arguments: ["@doctrine.orm.entity_manager","@concerto_panel.ScheduledTask_metadata"]
  concerto_panel.Administration_service:
    class: Concerto\PanelBundle\Service\AdministrationService
    arguments: ["@concerto_panel.AdministrationSetting_repository","@concerto_panel.Message_repository","@security.authorization_checker","%administration%","%version%","%kernel.root_dir%","@templating","@concerto_panel.TestSessionLog_repository","@doctrine","@concerto_panel.ScheduledTask_repository","@kernel","@Concerto\\APIBundle\\Repository\\ClientRepository","%test_runner_settings%"]


  concerto_panel.Maintenance_service:
    class: Concerto\PanelBundle\Service\MaintenanceService
    arguments: ["%administration%"]
    
# LoadBalancer
  concerto_panel.LoadBalancer_service:
    class: Concerto\PanelBundle\Service\LoadBalancerService
    arguments: ["@concerto_panel.TestSession_repository", "%test_nodes%", "@concerto_test.TestSessionCount_service"]
    
# ImportService
  concerto_panel.import_service:
      class: Concerto\PanelBundle\Service\ImportService
      arguments: ["@doctrine.orm.entity_manager", "@concerto_panel.DataTable_service", "@concerto_panel.Test_service", "@concerto_panel.TestNode_service", "@concerto_panel.TestNodePort_service", "@concerto_panel.TestNodeConnection_service", "@concerto_panel.TestVariable_service", "@concerto_panel.TestWizard_service", "@concerto_panel.TestWizardStep_service", "@concerto_panel.TestWizardParam_service", "@concerto_panel.ViewTemplate_service", "%version%"]
      
#   ExportService
  concerto_panel.export_service:
      class: Concerto\PanelBundle\Service\ExportService
      arguments: ["@concerto_panel.DataTable_service", "@concerto_panel.Test_service", "@concerto_panel.TestNode_service", "@concerto_panel.TestNodePort_service", "@concerto_panel.TestNodeConnection_service", "@concerto_panel.TestVariable_service", "@concerto_panel.TestWizard_service", "@concerto_panel.TestWizardStep_service", "@concerto_panel.TestWizardParam_service", "@concerto_panel.ViewTemplate_service", "%version%"]
    
#   RDataCacheService
  concerto_panel.r_data_cache_service:
    class: Concerto\PanelBundle\Service\RDataCacheService
    
#   Configuration verifier service
  concerto_panel.system_check_service:
    class: Concerto\PanelBundle\Service\SystemCheckService
    
  concerto_panel.test_runner_service:
    class: Concerto\PanelBundle\Service\TestRunnerService
    arguments: ["%kernel.environment%","%panel_nodes%","@logger","@concerto_panel.TestSession_service", "@concerto_panel.LoadBalancer_service"]
    
#   Controllers
  Concerto\PanelBundle\Controller\DataTableController:
    arguments:
      $environment: "%kernel.environment%"
    public: true

  Concerto\PanelBundle\Controller\TestController:
    arguments:
      $environment: "%kernel.environment%"
    public: true

  Concerto\PanelBundle\Controller\TestWizardController:
    arguments:
      $environment: "%kernel.environment%"
    public: true

  Concerto\PanelBundle\Controller\ViewTemplateController:
    arguments:
      $environment: "%kernel.environment%"
    public: true

  Concerto\PanelBundle\Controller\DialogController:
    arguments:
      $rootDir: "%kernel.root_dir%"
    public: true

  Concerto\PanelBundle\Controller\TestRunnerController:
    arguments:
      $environment: "%kernel.environment%"
      $settings: "%test_runner_settings%"
    public: true

#aliases
  Concerto\PanelBundle\Service\AdministrationService: '@concerto_panel.Administration_service'
  Concerto\PanelBundle\Service\DataTableService: '@concerto_panel.DataTable_service'
  Concerto\PanelBundle\Service\ImportService: '@concerto_panel.import_service'
  Concerto\PanelBundle\Service\ExportService: '@concerto_panel.export_service'
  Concerto\PanelBundle\Service\UserService: '@concerto_panel.User_service'
  Concerto\PanelBundle\Service\FileService: '@concerto_panel.file_service'
  Concerto\PanelBundle\Service\PanelService: '@concerto_panel.panel_service'
  Concerto\PanelBundle\Service\HomeService: '@concerto_panel.home_service'
  Concerto\PanelBundle\Service\TestService: '@concerto_panel.Test_service'
  Concerto\PanelBundle\Service\TestWizardService: '@concerto_panel.TestWizard_service'
  Concerto\PanelBundle\Service\TestNodeConnectionService: '@concerto_panel.TestNodeConnection_service'
  Concerto\PanelBundle\Service\TestNodeService: '@concerto_panel.TestNode_service'
  Concerto\PanelBundle\Service\TestNodePortService: '@concerto_panel.TestNodePort_service'
  Concerto\PanelBundle\Service\TestVariableService: '@concerto_panel.TestVariable_service'
  Concerto\PanelBundle\Service\TestRunnerService: '@concerto_panel.test_runner_service'
  Concerto\PanelBundle\Service\TestSessionService: '@concerto_panel.TestSession_service'
  Concerto\PanelBundle\Service\TestSessionLogService: '@concerto_panel.TestSessionLog_service'
  Concerto\PanelBundle\Service\TestWizardParamService: '@concerto_panel.TestWizardParam_service'
  Concerto\PanelBundle\Service\TestWizardStepService: '@concerto_panel.TestWizardStep_service'
  Concerto\PanelBundle\Service\ViewTemplateService: '@concerto_panel.ViewTemplate_service'
  Concerto\PanelBundle\DAO\DBDataDAO: '@concerto_panel.db_data_dao'
  Concerto\PanelBundle\DAO\DBStructureDAO: '@concerto_panel.db_structure_dao'
    
#security

  security.access.object_voter:
    class:      Concerto\PanelBundle\Security\ObjectVoter
    public:     false
    tags:
      - { name: security.voter }
  security.access.user_voter:
    class:      Concerto\PanelBundle\Security\UserVoter
    public:     false
    tags:
      - { name: security.voter }