concerto_api:
    resource: "@ConcertoAPIBundle/Resources/config/routing.yml"
    prefix:   /

concerto_test:
    resource: "@ConcertoTestBundle/Resources/config/routing.yml"
    prefix:   /

concerto_panel_data_table:
    resource: "@ConcertoPanelBundle/Resources/config/DataTable/routing.yml"
    prefix:   /admin/

concerto_panel_home:
    resource: "@ConcertoPanelBundle/Resources/config/Home/routing.yml"
    prefix: /

concerto_panel_admin:
    resource: "@ConcertoPanelBundle/Resources/config/Panel/routing.yml"
    prefix:   /

concerto_panel_test:
    resource: "@ConcertoPanelBundle/Resources/config/Test/routing.yml"
    prefix:   /admin/
    
concerto_panel_test_node:
    resource: "@ConcertoPanelBundle/Resources/config/TestNode/routing.yml"
    prefix:   /admin/
    
concerto_panel_test_node_connection:
    resource: "@ConcertoPanelBundle/Resources/config/TestNodeConnection/routing.yml"
    prefix:   /admin/
    
concerto_panel_test_node_port:
    resource: "@ConcertoPanelBundle/Resources/config/TestNodePort/routing.yml"
    prefix:   /admin/
    
concerto_panel_test_wizard:
    resource: "@ConcertoPanelBundle/Resources/config/TestWizard/routing.yml"
    prefix:   /admin/
    
concerto_panel_test_wizard_step:
    resource: "@ConcertoPanelBundle/Resources/config/TestWizardStep/routing.yml"
    prefix:   /admin/

concerto_panel_test_wizard_param:
    resource: "@ConcertoPanelBundle/Resources/config/TestWizardParam/routing.yml"
    prefix:   /admin/

concerto_panel_test_session_log:
    resource: "@ConcertoPanelBundle/Resources/config/TestSessionLog/routing.yml"
    prefix:   /admin/
    
concerto_panel_test_variable:
    resource: "@ConcertoPanelBundle/Resources/config/TestVariable/routing.yml"
    prefix:   /admin/
    
concerto_panel_user:
    resource: "@ConcertoPanelBundle/Resources/config/User/routing.yml"
    prefix:   /admin/
    
concerto_panel_view_template:
    resource: "@ConcertoPanelBundle/Resources/config/ViewTemplate/routing.yml"
    prefix:   /admin/

concerto_panel_test_session:
    resource: "@ConcertoPanelBundle/Resources/config/TestSession/routing.yml"
    prefix:   /
    
concerto_panel_file_browser:
    resource: "@ConcertoPanelBundle/Resources/config/FileBrowser/routing.yml"
    prefix:   /admin/

concerto_panel_dialog:
    resource: "@ConcertoPanelBundle/Resources/config/Dialog/routing.yml"
    prefix:   /admin/
    
concerto_panel_test_runner:
    resource: "@ConcertoPanelBundle/Resources/config/TestRunner/routing.yml"
    prefix:   /
    
concerto_panel_administration:
    resource: "@ConcertoPanelBundle/Resources/config/Administration/routing.yml"
    prefix:   /admin/

routing_custom:
    resource: routing_custom.yml

remove_trailing_slash:
    path: /{url}
    defaults: { _controller: ConcertoPanelBundle:Redirect:removeTrailingSlash }
    requirements:
        url: .*/$
    methods: [GET]