test_runner_start:
    path: /test/{test_slug}/{params}
    defaults: { _controller: concerto_panel.test_runner_controller:startNewTestAction, params: "{}", test_name: null }

test_runner_start_name:
    path: /test_n/{test_name}/{params}
    defaults: { _controller: concerto_panel.test_runner_controller:startNewTestAction, params: "{}", test_slug: null }
    
test_runner_start_debug:
    path: /admin/test/{test_slug}/debug/{params}
    defaults: { _controller: concerto_panel.test_runner_controller:startNewDebugTestAction, params: "{}" }
    
test_runner_session_start:
    path: /test/{test_slug}/session/start/{params}
    defaults: { _controller: concerto_panel.test_runner_controller:startNewSessionAction, params: "{}", test_name: null }
    methods:  [POST]

test_runner_session_start_name:
    path: /test_n/{test_name}/session/start/{params}
    defaults: { _controller: concerto_panel.test_runner_controller:startNewSessionAction, params: "{}", test_slug: null }
    methods:  [POST]
    
test_runner_session_start_debug:
    path: /admin/test/{test_slug}/session/start/debug/{params}
    defaults: { _controller: concerto_panel.test_runner_controller:startNewDebugSessionAction, params: "{}" }
    methods:  [POST]
    
test_runner_session_submit:
    path: /test/session/{session_hash}/submit
    defaults: { _controller: concerto_panel.test_runner_controller:submitToSessionAction }
    methods:  [POST]

test_runner_worker:
    path: /test/session/{session_hash}/worker
    defaults: { _controller: concerto_panel.test_runner_controller:backgroundWorkerAction }
    methods:  [POST]
    
test_runner_session_keepalive:
    path: /test/session/{session_hash}/keepalive
    defaults: { _controller: concerto_panel.test_runner_controller:keepAliveSessionAction }
    methods:  [POST]

test_runner_session_kill:
    path: /test/session/{session_hash}/kill
    defaults: { _controller: concerto_panel.test_runner_controller:killSessionAction }
    methods:  [POST]
    
test_runner_session_results:
    path: /test/session/{session_hash}/results
    defaults: { _controller: concerto_panel.test_runner_controller:resultsFromSessionAction }
    methods:  [POST]
    
test_runner_log_error:
    path: /test/session/{session_hash}/log
    defaults: { _controller: concerto_panel.test_runner_controller:logErrorAction }
    methods:  [POST]
    
test_runner_upload_file:
    path: /test/session/{session_hash}/upload
    defaults: { _controller: concerto_panel.test_runner_controller:uploadFileAction }
    methods:  [POST,OPTIONS]