DataTable_object:
    path: /DataTable/fetch/{object_id}/{format}
    defaults: { _controller: concerto_panel.DataTable_controller:objectAction, format: json }

DataTable_collection:
    path: /DataTable/collection/{format}
    defaults: { _controller: concerto_panel.DataTable_controller:collectionAction, format: json }

DataTable_form:
    path: /DataTable/form/{action}
    defaults: { _controller: concerto_panel.DataTable_controller:formAction, action: edit }
    
DataTable_save:
    path: /DataTable/{object_id}/save
    defaults: { _controller: concerto_panel.DataTable_controller:saveAction }
    methods:  [POST]
    
DataTable_copy:
    path: /DataTable/{object_id}/copy
    defaults: { _controller: concerto_panel.DataTable_controller:copyAction }
    methods:  [POST]
    
DataTable_delete:
    path: /DataTable/{object_ids}/delete
    defaults: { _controller: concerto_panel.DataTable_controller:deleteAction } 
    methods:  [POST]
    
DataTable_column_object:
    path: /DataTable/fetch/{table_id}/column/{column_name}/{format}
    defaults: { _controller: concerto_panel.DataTable_controller:fetchColumnAction, format: json }

DataTable_columns_collection:
    path: /DataTable/{table_id}/columns/collection
    defaults: { _controller: concerto_panel.DataTable_controller:columnsCollectionAction }
    
DataTable_data_section:
    path: /DataTable/{table_id}/data/section
    defaults: { _controller: concerto_panel.DataTable_controller:dataSectionAction }    
    
DataTable_data_collection:
    path: /DataTable/{table_id}/data/collection/{prefixed}
    defaults: { _controller: concerto_panel.DataTable_controller:dataCollectionAction, prefixed: 0 }
    
DataTable_column_delete:
    path: /DataTable/{table_id}/column/{column_names}/delete
    defaults: { _controller: concerto_panel.DataTable_controller:deleteColumnAction }
    methods:  [POST]
    
DataTable_column_save:
    path: /DataTable/{table_id}/column/{column_name}/save
    defaults: { _controller: concerto_panel.DataTable_controller:saveColumnAction }
    methods:  [POST]
    
DataTable_row_delete:
    path: /DataTable/{table_id}/row/{row_ids}/delete
    defaults: { _controller: concerto_panel.DataTable_controller:deleteRowAction }
    methods:  [POST]
    
DataTable_truncate:
    path: /DataTable/{table_id}/truncate
    defaults: { _controller: concerto_panel.DataTable_controller:truncateAction }
    methods:  [POST]
    
DataTable_row_insert:
    path: /DataTable/{table_id}/row/insert
    defaults: {_controller: concerto_panel.DataTable_controller:insertRowAction }
    methods:  [POST]
    
DataTable_row_update:
    path: /DataTable/{table_id}/row/{row_id}/update/{prefixed}
    defaults: {_controller: concerto_panel.DataTable_controller:updateRowAction, prefixed: 0 }
    methods:  [POST]
    
DataTable_export:
    path: /DataTable/{object_ids}/export/{format}
    defaults: { _controller: concerto_panel.DataTable_controller:exportAction, format: 'compressed' }
    
DataTable_import:
    path: /DataTable/import
    defaults: { _controller: concerto_panel.DataTable_controller:importAction }
    methods:  [POST]
    
DataTable_pre_import_status:
    path: /DataTable/import/status
    defaults: { _controller: concerto_panel.DataTable_controller:preImportStatusAction }
    
DataTable_csv_import:
    path: /DataTable/{table_id}/csv/{restructure}/{header}/{delimiter}/{enclosure}/import
    defaults: { _controller: concerto_panel.DataTable_controller:importCsvAction }
    methods:  [POST]