AdministrationSetting_map:
    path: /AdministrationSetting/map
    defaults: { _controller: concerto_panel.Administration_controller:settingsMapAction}
    
AdministrationSetting_map_update:
    path: /AdministrationSetting/map/update
    defaults: { _controller: concerto_panel.Administration_controller:updateSettingsMapAction}
    methods:  [POST]