AdministrationSetting_map:
    path: /AdministrationSetting/map
    defaults: { _controller: concerto_panel.Administration_controller:settingsMapAction}
    
AdministrationSetting_map_update:
    path: /AdministrationSetting/map/update
    defaults: { _controller: concerto_panel.Administration_controller:updateSettingsMapAction}
    methods:  [POST]
    
Administration_session_count_collection:
    path: /Administration/SessionCount/{filter}/collection
    defaults: { _controller: concerto_panel.Administration_controller:sessionCountCollectionAction, filter: "{}"}
    
AdministrationSetting_session_count_clear:
    path: /AdministrationSetting/SessionCount/clear
    defaults: { _controller: concerto_panel.Administration_controller:clearSessionCountAction}
    methods:  [POST]
    
Administration_messages_collection:
    path: /Administration/Messages/collection
    defaults: { _controller: concerto_panel.Administration_controller:messagesCollectionAction }
    
Administration_messages_delete:
    path: /Administration/Messages/{object_ids}/delete
    defaults: { _controller: concerto_panel.Administration_controller:deleteMessageAction }
    
Administration_messages_clear:
    path: /Administration/Messages/clear
    defaults: { _controller: concerto_panel.Administration_controller:clearMessagesAction }
    
Administration_tasks_collection:
    path: /Administration/ScheduledTask/collection
    defaults: { _controller: concerto_panel.Administration_controller:tasksCollectionAction }
    
Administration_tasks_backup:
    path: /Administration/ScheduledTask/backup
    defaults: { _controller: concerto_panel.Administration_controller:taskBackupAction }