AdministrationSetting_map:
    path: /AdministrationSetting/map
    defaults: { _controller: concerto_panel.Administration_controller:settingsMapAction}
    
AdministrationSetting_map_update:
    path: /AdministrationSetting/map/update
    defaults: { _controller: concerto_panel.Administration_controller:updateSettingsMapAction}
    methods:  [POST]
    
Administration_session_count_collection:
    path: /Administration/SessionCount/{filter}/collection
    defaults: { _controller: concerto_panel.Administration_controller:sessionCountCollectionAction, filter: "{}"}
    
AdministrationSetting_session_count_clear:
    path: /AdministrationSetting/SessionCount/clear
    defaults: { _controller: concerto_panel.Administration_controller:clearSessionCountAction}
    methods:  [POST]
    
Administration_messages_collection:
    path: /Administration/Messages/collection
    defaults: { _controller: concerto_panel.Administration_controller:messagesCollectionAction }