AdministrationSetting_map:
    path: /AdministrationSetting/map
    defaults: { _controller: concerto_panel.Administration_controller:settingsMapAction}
    
AdministrationSetting_map_update:
    path: /AdministrationSetting/map/update
    defaults: { _controller: concerto_panel.Administration_controller:updateSettingsMapAction}
    methods:  [POST]
    
Administration_session_count_collection:
    path: /Administration/SessionCount/{filter}/collection
    defaults: { _controller: concerto_panel.Administration_controller:sessionCountCollectionAction, filter: "{}"}
    
AdministrationSetting_session_count_clear:
    path: /AdministrationSetting/SessionCount/clear
    defaults: { _controller: concerto_panel.Administration_controller:clearSessionCountAction}
    methods:  [POST]
    
Administration_messages_collection:
    path: /Administration/Messages/collection
    defaults: { _controller: concerto_panel.Administration_controller:messagesCollectionAction }
    
Administration_messages_delete:
    path: /Administration/Messages/{object_ids}/delete
    defaults: { _controller: concerto_panel.Administration_controller:deleteMessageAction }
    
Administration_messages_clear:
    path: /Administration/Messages/clear
    defaults: { _controller: concerto_panel.Administration_controller:clearMessagesAction }
    
Administration_tasks_collection:
    path: /Administration/ScheduledTask/collection
    defaults: { _controller: concerto_panel.Administration_controller:tasksCollectionAction }
    
Administration_tasks_backup:
    path: /Administration/ScheduledTask/backup
    defaults: { _controller: concerto_panel.Administration_controller:taskBackupAction }
    
Administration_tasks_restore:
    path: /Administration/ScheduledTask/restore
    defaults: { _controller: concerto_panel.Administration_controller:taskRestoreAction }
    
Administration_tasks_content_upgrade:
    path: /Administration/ScheduledTask/content_upgrade
    defaults: { _controller: concerto_panel.Administration_controller:taskContentUpgradeAction }
    
Administration_tasks_platform_upgrade:
    path: /Administration/ScheduledTask/platform_upgrade
    defaults: { _controller: concerto_panel.Administration_controller:taskPlatformUpgradeAction }
 
Administration_tasks_package_install:
    path: /Administration/ScheduledTask/package_install
    defaults: { _controller: concerto_panel.Administration_controller:taskPackageInstallAction }
    
Administration_api_clients_collection:
    path: /Administration/api_clients/collection
    defaults: { _controller: concerto_panel.Administration_controller:apiClientCollectionAction }
    
Administration_api_clients_delete:
    path: /Administration/api_clients/{object_ids}/delete
    defaults: { _controller: concerto_panel.Administration_controller:deleteApiClientAction }
    
Administration_api_clients_clear:
    path: /Administration/api_clients/clear
    defaults: { _controller: concerto_panel.Administration_controller:clearApiClientAction }
    
Administration_api_clients_add:
    path: /Administration/api_clients/add
    defaults: { _controller: concerto_panel.Administration_controller:addApiClientAction }
    
Administration_packages_status:
    path: /Administration/packages/status
    defaults: { _controller: concerto_panel.Administration_controller:packagesStatusAction }