TestWizard_object:
    path: /TestWizard/fetch/{object_id}/{format}
    defaults: { _controller: concerto_panel.TestWizard_controller:objectAction, format: json }

TestWizard_collection:
    path: /TestWizard/collection/{format}
    defaults: { _controller: concerto_panel.TestWizard_controller:collectionAction, format: json }

TestWizard_form: 
    path: /TestWizard/form/{action}
    defaults: { _controller: concerto_panel.TestWizard_controller:formAction, action: edit }
    
TestWizard_save:
    path: /TestWizard/{object_id}/save
    defaults: { _controller: concerto_panel.TestWizard_controller:saveAction }
    methods:  [POST]
    
TestWizard_copy:
    path: /TestWizard/{object_id}/copy
    defaults: { _controller: concerto_panel.TestWizard_controller:copyAction }
    methods:  [POST]
    
TestWizard_delete:
    path: /TestWizard/{object_ids}/delete
    defaults: { _controller: concerto_panel.TestWizard_controller:deleteAction } 
    methods:  [POST]
    
TestWizard_export:
    path: /TestWizard/{object_ids}/export/{format}
    defaults: { _controller: concerto_panel.TestWizard_controller:exportAction, format: compressed }
    
TestWizard_import:
    path: /TestWizard/import
    defaults: { _controller: concerto_panel.TestWizard_controller:importAction }
    methods:  [POST]
    
TestWizard_pre_import_status:
    path: /TestWizard/import/status
    defaults: { _controller: concerto_panel.TestWizard_controller:preImportStatusAction }