parameters:

services:
    concerto_test.command.start_process_command:
        class: Concerto\TestBundle\Command\StartProcessCommand
        tags:
            -  { name: console.command }
            
    concerto_test.SessionCount_metadata:
        class: Doctrine\ORM\Mapping\ClassMetadata
        arguments: ["Concerto\\TestBundle\\Entity\\SessionCount"]
    concerto_test.SessionCount_repository:
        class: Concerto\TestBundle\Repository\SessionCountRepository
        arguments: ["@doctrine.orm.entity_manager","@concerto_test.SessionCount_metadata"]
    concerto_test.SessionCount_service:
        class: Concerto\TestBundle\Service\SessionCountService
        arguments: ["@concerto_test.SessionCount_repository"]
        
    concerto_test.r_runner_service:
        class: Concerto\TestBundle\Service\RRunnerService
        arguments: ["%kernel.root_dir%","%panel_nodes%","%test_nodes%","%test_runner_settings%","@doctrine", "@logger"]
    concerto_test.r_runner_controller:
        class: Concerto\TestBundle\Controller\RRunnerController
        arguments: ["@templating","@concerto_test.r_runner_service", "@request", "@logger"]
        scope: request
        
    concerto_test.command.log_session_count_command:
        class: Concerto\TestBundle\Command\LogSessionCountCommand
        arguments: ["@concerto_test.r_runner_service","@concerto_test.SessionCount_service"]
        tags:
            -  { name: console.command }