parameters:

services:
    concerto_test.command.start_process_command:
        class: Concerto\TestBundle\Command\StartProcessCommand
        tags:
            -  { name: console.command }
        
    concerto_test.r_runner_service:
        class: Concerto\TestBundle\Service\RRunnerService
        arguments: ["%kernel.root_dir%","%panel_nodes%","%test_nodes%","%test_runner_settings%","@doctrine", "@logger"]
    concerto_test.r_runner_controller:
        class: Concerto\TestBundle\Controller\RRunnerController
        arguments: ["@templating","@concerto_test.r_runner_service", "@request", "@logger"]
        scope: request