parameters:

services:        
    concerto_test.TestSessionCount_metadata:
        class: Doctrine\ORM\Mapping\ClassMetadata
        arguments: ["Concerto\\TestBundle\\Entity\\TestSessionCount"]
    concerto_test.TestSessionCount_repository:
        class: Concerto\TestBundle\Repository\TestSessionCountRepository
        arguments: ["@doctrine.orm.entity_manager","@concerto_test.TestSessionCount_metadata"]
    concerto_test.TestSessionCount_service:
        class: Concerto\TestBundle\Service\TestSessionCountService
        arguments: ["@concerto_test.TestSessionCount_repository"]
        
    concerto_test.r_runner_service:
        class: Concerto\TestBundle\Service\RRunnerService
        arguments: ["%kernel.root_dir%","%panel_nodes%","%test_runner_settings%","@doctrine","@logger","@concerto_panel.Administration_service","@concerto_test.TestSessionCount_service","@concerto_panel.LoadBalancer_service"]
    concerto_test.r_runner_controller:
        class: Concerto\TestBundle\Controller\RRunnerController
        arguments: ["@templating","@concerto_test.r_runner_service", "@request", "@logger"]
        scope: request
        
    concerto_test.command.log_session_count_command:
        class: Concerto\TestBundle\Command\LogSessionCountCommand
        arguments: ["@concerto_test.TestSessionCount_service"]
        tags:
            -  { name: console.command }
    concerto_test.command.start_process_command:
        class: Concerto\TestBundle\Command\StartProcessCommand
        arguments: ["@concerto_test.TestSessionCount_service"]
        tags:
            -  { name: console.command }